// <auto-generated />
namespace CRUDreborn.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class date_on_venda : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(date_on_venda));
        
        string IMigrationMetadata.Id
        {
            get { return "201804032042030_date_on_venda"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
