// <auto-generated />
namespace CRUDreborn.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class _1nmigration : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_1nmigration));
        
        string IMigrationMetadata.Id
        {
            get { return "201803271738246_1-n migration"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
